### ISSUE TITLE
How is this `prefix` given

### ISSUE THREAD

**Issue by shaoyuyoung** [JetBrains-Research/commit_message_generation#8]
Dear authors,

thank you for your interesting research which is really inspiring

I just have one small question about data pre-processing (or maybe model inference).  I want to know how the `prefix`  which is in the model input is given. In your paper, Fig1 gives an illustration of this. But I notice that the prefix in Fig 1 seems to be exactly the same as the prefix part in the ground truth(i.e., `fix(doc`). For  `fix(doc`, how is the length of such a prefix arrived at, and why can't it be shorter or longer? (i.e., `fix(` or `fix(docs):` ).

Moreover, in model training, did you use prefixes and histories?

Looking forward to your reply. Thx in advance!

**Comment by saridormi** [comment]
Hello! Thank you for taking interest in our work :)

In our experiments, we constructed the prefixes sort of artificially by taking the first X% characters of each message as prefix and treating the remaining part as target (X here is what we call "context ratio" throughout the results section). We experimented with three different values of X: 
* 0% (no prefix at all, generation)
* 25%
* 50%

This concerns only evaluation stage; during training, we used full commit messages, exactly the same as when training for commit message generation. If you're interested, here is [the code](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/data_collators/data_collator_test.py#L40) that is responsible for prefixes construction during evaluation. 

In a real-world completion scenario, it could be a task of its own to determine when exactly the completion model should and should not be invoked, maybe guided by some heuristics or even a separate model.

As for the history, we considered two configurations:
* history is used during both training and evaluation
* history is not used during both training and evaluation

You can find the code responsible for constructing inputs with history during training [here](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/data_collators/data_collator_train.py#L47).

I hope that answers your questions, but feel free to let me know if I can be of help!

**Comment by shaoyuyoung** [comment]
Thank you for your detailed information. It is really enlightening to me.

Thx again!
